version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "01:30"
      timezone: Australia/Perth
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    groups:
      production-minor-patch:
        dependency-type: production
        update-types: [minor, patch]
      development-minor-patch:
        dependency-type: development
        update-types: [minor, patch]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "01:45"
      timezone: Australia/Perth
