export const pillars = [
  { id: 'nourish', label: 'Nourish', short: 'Something workable to eat', tone: 'clay' },
  { id: 'regulate', label: 'Regulate', short: 'Reduce the load', tone: 'rose' },
  { id: 'begin', label: 'Begin', short: 'Make contact with the task', tone: 'gold' },
  { id: 'connect', label: 'Connect', short: 'Say what keeps circling', tone: 'plum' },
  { id: 'move', label: 'Move', short: 'Move without measurement', tone: 'olive' },
  { id: 'understand', label: 'Understand', short: 'The science, honestly', tone: 'blue' },
]

// `barriers` names what is actually in the way (used by Explore's barrier filter and by
// Today's check-in-aware sorting); `effort` is a 1-3 scale derived from `duration` so cards
// can carry a quick visual weight cue; `evidenceId` links to the matching entry in
// `evidenceNotes` below, when one genuinely supports this card's content — not every card
// gets one, because not every card has a citable source behind it.
export const rightNowPaths = [
  { id: 'unsent-conversation', pillar: 'connect', title: 'I keep rehearsing what I need to say', subtitle: 'The perfect moment has not come. Let’s make a bridge to the real one.', duration: '4 min', icon: 'MessageCircleMore', barriers: ['words', 'shame'], effort: 2, evidenceId: 'lived-experience-review' },
  { id: 'forgot-eat', pillar: 'nourish', title: 'I forgot to eat', subtitle: 'Start where you are. No making up for it.', duration: '2 min', icon: 'Utensils', barriers: ['time-blindness', 'decision-load'], effort: 1, evidenceId: 'aadpa-lifestyle' },
  { id: 'cant-start', pillar: 'begin', title: 'I know what to do. I still can’t begin.', subtitle: 'Knowing and starting are different jobs.', duration: '5 min', icon: 'Play', barriers: ['activation', 'decision-load'], effort: 2, evidenceId: 'lived-experience-review' },
  { id: 'too-many-tabs', pillar: 'regulate', title: 'My brain has too many tabs open', subtitle: 'Stop solving. Reduce the number of things asking for you.', duration: '3 min', icon: 'Layers3', barriers: ['decision-load', 'sensory-load'], effort: 1, evidenceId: 'lived-experience-review' },
  { id: 'nothing-manageable', pillar: 'nourish', title: 'Nothing sounds manageable', subtitle: 'Lower the sensory and decision load.', duration: '3 min', icon: 'Soup', barriers: ['sensory-load', 'decision-load'], effort: 1, evidenceId: 'aadpa-lifestyle' },
  { id: 'small-mistake', pillar: 'connect', title: 'A small mistake feels enormous', subtitle: 'Separate the moment from the story your body attached to it.', duration: '4 min', icon: 'HeartHandshake', barriers: ['shame'], effort: 2, evidenceId: 'rejection-sensitivity' },
  { id: 'lost-the-day', pillar: 'begin', title: 'I started one thing and lost the whole day', subtitle: 'Hyperfocus needs a landing—not a punishment.', duration: '4 min', icon: 'TimerReset', barriers: ['time-blindness', 'activation'], effort: 2, evidenceId: 'lived-experience-review' },
  { id: 'out-of-sight', pillar: 'begin', title: 'If I can’t see it, it leaves my brain', subtitle: 'Make the next cue visible without turning the room into a reminder wall.', duration: '3 min', icon: 'Eye', barriers: ['time-blindness', 'decision-load'], effort: 1, evidenceId: 'lived-experience-review' },
  { id: 'overwhelmed', pillar: 'regulate', title: 'Everything feels too loud', subtitle: 'Less input. One point of contact.', duration: '3 min', icon: 'Waves', barriers: ['sensory-load', 'decision-load'], effort: 1, evidenceId: 'lived-experience-review' },
  { id: 'med-appetite', pillar: 'nourish', title: 'My medication changed my appetite', subtitle: 'A gentle rhythm and the right clinical support.', duration: '4 min', icon: 'Clock3', barriers: ['time-blindness', 'decision-load'], effort: 2, evidenceId: 'aadpa-lifestyle' },
  { id: 'waiting-urgency', pillar: 'begin', title: 'I’m waiting for the pressure to arrive', subtitle: 'Borrow activation before panic has to provide it.', duration: '5 min', icon: 'Gauge', barriers: ['activation', 'time-blindness'], effort: 2, evidenceId: 'lived-experience-review' },
  { id: 'systems-collapse', pillar: 'begin', title: 'I have a system for every system', subtitle: 'When the support structure becomes another task.', duration: '4 min', icon: 'ListChecks', barriers: ['decision-load', 'activation'], effort: 2, evidenceId: 'lived-experience-review' },
  { id: 'look-capable', pillar: 'regulate', title: 'I’m exhausted from looking capable', subtitle: 'High functioning can still cost too much.', duration: '5 min', icon: 'BatteryLow', barriers: ['shame', 'decision-load'], effort: 2, evidenceId: 'rejection-sensitivity' },
  { id: 'reply-late', pillar: 'connect', title: 'I left it too long to reply', subtitle: 'The shame grows while the message gets no easier.', duration: '3 min', icon: 'MessageSquareReply', barriers: ['shame', 'words'], effort: 1, evidenceId: 'rejection-sensitivity' },
  { id: 'sensory-anchor', pillar: 'regulate', title: 'My body needs something steady to hold', subtitle: 'Try a quiet tactile anchor without claiming it will fix the feeling.', duration: '3 min', icon: 'Hand', barriers: ['sensory-load'], effort: 1, evidenceId: 'lived-experience-review' },
  { id: 'move-reset', pillar: 'move', title: 'I need to move or change the channel', subtitle: 'No goals, pace or calories attached.', duration: '4 min', icon: 'Footprints', barriers: ['activation', 'sensory-load'], effort: 2, evidenceId: 'lived-experience-review' },
  { id: 'wind-down', pillar: 'regulate', title: 'My brain won’t clock off', subtitle: 'Build a softer off-ramp for unfinished loops.', duration: '5 min', icon: 'Moon', barriers: ['sensory-load', 'decision-load'], effort: 2, evidenceId: 'lived-experience-review' },
  { id: 'research', pillar: 'understand', title: 'I want the research without the wellness hype', subtitle: 'What we know, what is preliminary, and who to ask.', duration: '6 min', icon: 'BookOpen', barriers: ['decision-load'], effort: 3, evidenceId: 'gow-nutrition' },
]

export const toolDetails = {
  'unsent-conversation': {
    eyebrow: 'The unsent conversation loop',
    title: 'Thinking about saying it is not the same as saying it.',
    intro: 'You may have replayed the conversation so often that it feels as though you have been communicating. Meanwhile, the other person only experiences the silence. We are not finding perfect words; we are making contact.',
    steps: [
      ['Name', 'What is the smallest true thing?', 'Not the full history. Try one sentence: “There is something I have been trying to find the words for.”'],
      ['Lower', 'Choose a lower-pressure channel', 'A short message can ask for a time to talk. It does not need to contain the whole conversation.'],
      ['Signal', 'Say what the delay means', 'Try: “My delay is about overthinking and fear of getting it wrong—not about this not mattering.”'],
      ['Invite', 'Give the other person a doorway', 'Ask when they have capacity, or whether they would prefer to talk, read or listen. Their needs still count too.'],
    ],
    cta: { label: 'Use the four-minute say-it bridge', action: 'talk-timer' },
    note: 'This tool is not for unsafe relationships, coercion or family violence. Use a trusted professional or specialist support service when direct contact could increase risk.',
  },
  'forgot-eat': {
    eyebrow: 'A gentle restart',
    title: 'You haven’t failed. You need a next step.',
    intro: 'An ADHD day can move quickly while body signals stay quiet. There is nothing to compensate for. We are only looking for something workable now.',
    steps: [
      ['1', 'Make it reachable', 'Bring one familiar option into sight. Packaged, frozen, delivered and assembled all count.'],
      ['2', 'Reduce the decision', 'Choose the option with the least preparation or clean-up—not the one you think you “should” choose.'],
      ['3', 'Add company if it helps', 'Sit near someone, call a safe person, or put on a familiar show. Company can make beginning feel smaller.'],
      ['4', 'Return at the next cue', 'You do not need to fix the whole day. Let the next rhythm cue be the next moment.'],
    ],
    cta: { label: 'Open a 10-minute eating companion', action: 'timer' },
    note: 'If appetite loss, dizziness, fainting, rapid weight change, vomiting or difficulty eating is ongoing, speak with your GP or prescriber.',
  },
  'cant-start': {
    eyebrow: 'Knowing is not beginning',
    title: 'Make the first movement almost too small.',
    intro: 'This is not a motivation test. A task can be fully understood and still have too many entry steps, too little interest or too much emotional weight.',
    steps: [
      ['See', 'Name a movement the camera could see', 'Not “sort my life”. Try: open the document, put the plate on the bench, or find the first email.'],
      ['Shrink', 'Make contact the whole goal', 'You are allowed to stop after one touch. Continuing is an option, not the price of starting.'],
      ['Borrow', 'Use external activation', 'A timer, body double, familiar music or someone quietly present can hold the starting line.'],
      ['Leave', 'Make re-entry visible', 'Before stopping, leave one clear clue for the next version of you.'],
    ],
    cta: { label: 'Borrow five gentle minutes', action: 'starter-timer' },
  },
  'too-many-tabs': {
    eyebrow: 'Internal traffic',
    title: 'The problem may be volume, not priority.',
    intro: 'When every open loop is speaking at once, choosing the most important one can become another impossible task. First reduce the number of voices.',
    steps: [
      ['Park', 'Put the loops somewhere visible', 'Write fragments, not a polished list. Your brain does not need to keep rehearsing them.'],
      ['Mute', 'Reduce one source of incoming information', 'Close one screen, silence one notification or move away from one conversation.'],
      ['Choose', 'Find the thing with the nearest consequence', 'Not the biggest life goal—just what needs contact next.'],
      ['Return', 'Keep the parked list closed for ten minutes', 'You are not abandoning it. You are giving one task enough room to exist.'],
    ],
    cta: { label: 'Take a three-minute tab sort', action: 'sort-timer' },
  },
  'nothing-manageable': {
    eyebrow: 'Sensory and decision load',
    title: 'Nourishment is the aim. Impressive is not.',
    intro: 'Texture, smell, temperature, effort and uncertainty can all become barriers. A short list of reliable options can be an access tool.',
    steps: [
      ['1', 'Pick a temperature', 'Would cold, room temperature or warm feel least demanding?'],
      ['2', 'Pick a texture', 'Would smooth, crunchy, soft, plain or sippable feel most predictable?'],
      ['3', 'Pick the effort ceiling', 'No preparation, assemble-only, microwave, or a little cooking?'],
      ['4', 'Use a reliable option', 'Familiarity is information. You can save what works and return to it on another hard day.'],
    ],
    cta: { label: 'Find a workable idea', action: 'fuel-finder' },
  },
  'small-mistake': {
    eyebrow: 'When feedback lands in the body',
    title: 'The feeling is real. The meaning is not settled yet.',
    intro: 'Criticism, ambiguity or a small error can rapidly become “I have ruined everything”. Rejection sensitivity is a lived-experience term, not a formal diagnosis, and it is not unique to ADHD.',
    steps: [
      ['Body', 'Name what happened physically', 'Heat, sinking, buzzing, tears or an urge to disappear are information—not proof of the story.'],
      ['Facts', 'Write only what was observable', 'What was actually said or done, without adding what it means about your worth or the relationship?'],
      ['Time', 'Delay repair that comes from panic', 'You can acknowledge the message now and return when your body is less activated.'],
      ['Repair', 'Use proportionate words', 'A mistake may need an apology or correction. It does not require self-erasure.'],
    ],
    cta: { label: 'Use the four-minute repair pause', action: 'shame-timer' },
  },
  'lost-the-day': {
    eyebrow: 'A landing for hyperfocus',
    title: 'Coming out of focus can feel like waking in the wrong room.',
    intro: 'Deep focus can be useful and still make time, body cues and other commitments disappear. The next move is a landing sequence—not a lecture.',
    steps: [
      ['Orient', 'Look for the current time and place', 'Say the time, day and what changed while your attention was elsewhere.'],
      ['Body', 'Check the quiet basics', 'Bathroom, drink, something to eat, medication routine, pain or temperature.'],
      ['Repair', 'Find one consequence that needs contact', 'A short message or calendar change may be enough for now.'],
      ['Leave', 'Save the return point', 'Write one line about where to restart so stopping does not feel like losing the work.'],
    ],
    cta: { label: 'Take a four-minute landing', action: 'landing-timer' },
  },
  'out-of-sight': {
    eyebrow: 'Make memory external',
    title: 'Visible is not childish. Visible is accessible.',
    intro: 'Working memory can drop an intention as soon as the cue disappears. The answer is not keeping everything visible; it is choosing one cue at the point where action happens.',
    steps: [
      ['One', 'Choose the one thing that must reappear', 'Not every obligation. Pick the next handover your future self needs.'],
      ['Place', 'Put the cue where the action begins', 'The item by the door, the note on the laptop, the bowl near the keys.'],
      ['Label', 'Use an action, not a category', '“Take this to work” is easier to enter than “admin”.'],
      ['Reset', 'Remove expired cues', 'Old reminders become visual wallpaper. A cue works because it is current.'],
    ],
    cta: { label: 'Put one cue in place', action: 'one-thing' },
  },
  overwhelmed: {
    eyebrow: 'Less input, first',
    title: 'You do not have to organise the whole storm.',
    intro: 'Anchor will not decide what your nervous system “is”. This is simply a short way to reduce input and find one point of contact.',
    steps: [
      ['1', 'Let your eyes land', 'Find one still object. Notice its edges, colour and distance from you.'],
      ['2', 'Reduce one source of input', 'Lower a light, silence one notification, sit down, or move somewhere quieter if you can.'],
      ['3', 'Find the body’s support', 'Notice the chair, floor or wall holding some of your weight. No special breathing required.'],
      ['4', 'Choose only the next thing', 'A sip, a message, the bathroom, one bite, or nothing for one minute.'],
    ],
    cta: { label: 'Make a one-thing plan', action: 'one-thing' },
  },
  'med-appetite': {
    eyebrow: 'Medication and appetite',
    title: 'Appetite changes deserve support—not blame.',
    intro: 'Some people notice appetite changes while taking stimulant medication. Planned opportunities to eat may be more usable than waiting for a strong hunger signal.',
    steps: [
      ['1', 'Notice the timing', 'Without scoring or judging, notice when eating feels easier and when it becomes harder.'],
      ['2', 'Put support before the hard window', 'A visible option, reminder or prepared snack before appetite becomes harder can reduce the number of steps.'],
      ['3', 'Tell the prescriber', 'Persistent appetite loss or other side effects belong in medication monitoring. Do not change medication timing or dose through Anchor.'],
      ['4', 'Bring the whole pattern', 'A GP, prescriber or Accredited Practising Dietitian can consider symptoms, medication, health and your eating pattern together.'],
    ],
    cta: { label: 'Set an appetite-support cue', action: 'plan' },
    note: 'Anchor does not recommend medication changes, blood tests or supplements.',
  },
  'waiting-urgency': {
    eyebrow: 'When panic is the starter motor',
    title: 'You do not have to wait until the deadline becomes an emergency.',
    intro: 'Urgency can create the activation that interest or routine did not. We are borrowing some external pressure without recreating panic.',
    steps: [
      ['Witness', 'Tell one safe person the exact first step', 'A small social promise can make the task feel present.'],
      ['Clock', 'Use a short, visible finish line', 'Five minutes is enough. The timer is for contact, not completion.'],
      ['Consequence', 'Bring one real reason into view', 'Who or what becomes easier when this moves by one step?'],
      ['Close', 'Stop before you need catastrophe to keep going', 'Leave a re-entry cue and choose the next contact time.'],
    ],
    cta: { label: 'Borrow five minutes of urgency', action: 'starter-timer' },
  },
  'systems-collapse': {
    eyebrow: 'When organising becomes the task',
    title: 'A support system should remove work.',
    intro: 'Multiple calendars, abandoned planners and lists of lists can create more places to forget. The strongest system may be the one you will actually reopen.',
    steps: [
      ['Collect', 'Choose one temporary landing place', 'For today, put new commitments in one place only.'],
      ['Cut', 'Pause one duplicate system', 'Do not migrate everything. Just stop adding new information to one extra place.'],
      ['Surface', 'Keep only the next three actions visible', 'The archive can exist without sitting in your working memory.'],
      ['Review', 'Attach checking to something that already happens', 'Opening your laptop or making coffee can become the cue.'],
    ],
    cta: { label: 'Choose today’s one landing place', action: 'one-thing' },
  },
  'look-capable': {
    eyebrow: 'The cost of compensation',
    title: 'Looking organised is not the same as being okay.',
    intro: 'Perfectionism, over-preparing, people-pleasing and constant self-monitoring can hide difficulty while consuming the energy needed for the rest of life.',
    steps: [
      ['Cost', 'Name what “coping” is costing', 'Sleep, eating, recovery time, relationships, joy or the ability to do anything after work.'],
      ['Drop', 'Choose one performance you can safely reduce', 'An email can be good enough. A room can stay imperfect. A reply can be short.'],
      ['Ask', 'Request one concrete adjustment', 'Written instructions, a clearer deadline, fewer interruptions or a quieter environment.'],
      ['Recover', 'Put decompression on the plan', 'Recovery is part of functioning, not evidence that you failed at it.'],
    ],
    cta: { label: 'Take five minutes off-stage', action: 'offstage-timer' },
  },
  'reply-late': {
    eyebrow: 'The message shame spiral',
    title: 'Late is still allowed to become now.',
    intro: 'A missed reply can gather embarrassment until reopening it feels like facing a verdict. You do not need an elaborate explanation to re-enter contact.',
    steps: [
      ['Open', 'Read only the last message', 'Do not review the whole relationship before replying.'],
      ['Name', 'Use one honest sentence', '“I saw this, kept meaning to reply, and then felt awkward that it had been so long.”'],
      ['Answer', 'Respond to the actual question', 'Acknowledge what they needed instead of making them reassure you.'],
      ['Release', 'Let their response belong to them', 'Repair invites connection; it cannot control the outcome.'],
    ],
    cta: { label: 'Use the three-minute reply bridge', action: 'reply-timer' },
  },
  'sensory-anchor': {
    eyebrow: 'A portable point of contact',
    title: 'Give busy hands one quiet job.',
    intro: 'Some people find a predictable tactile sensation useful when input is high. This is a preference-based grounding option—not a treatment and not proof that a particular product works.',
    steps: [
      ['Choose', 'Find a neutral object', 'A smooth stone, fabric edge, cool mug, firm cushion or familiar fidget may be enough.'],
      ['Consent', 'Check whether the sensation helps', 'More pressure is not automatically better. Stop if it irritates, hurts or increases distress.'],
      ['Describe', 'Notice three physical qualities', 'Temperature, texture, weight, edges or movement. No need to force calm.'],
      ['Carry', 'Keep one option where overwhelm usually happens', 'Portable and familiar can matter more than specialised.'],
    ],
    cta: { label: 'Try a three-minute sensory anchor', action: 'sensory-timer' },
  },
  'move-reset': {
    eyebrow: 'Movement without measurement',
    title: 'Move in a way that gives something back.',
    intro: 'There are no rings to close here. Choose movement for sensation, transition, enjoyment or a change of scene—not to compensate for eating.',
    steps: [
      ['1', 'Pick the need', 'Do you want release, grounding, alertness, play or a change of room?'],
      ['2', 'Choose one small movement', 'Stretch your hands, shake out your shoulders, walk to the mailbox, or move to one song.'],
      ['3', 'Keep consent in the loop', 'Pain, dizziness, fatigue or “not today” are reasons to pause—not obstacles to overcome.'],
      ['4', 'Finish without earning', 'Stopping is complete. Movement does not need a number to count.'],
    ],
    cta: { label: 'Take a four-minute reset', action: 'move-timer' },
  },
  'wind-down': {
    eyebrow: 'A softer off-ramp',
    title: 'The day can end before every loop is closed.',
    intro: 'A busy brain may need visible signals that the day is changing. Choose one or two—not a perfect routine.',
    steps: [
      ['1', 'Park the open loops', 'Write the unfinished things somewhere you can trust tomorrow.'],
      ['2', 'Change one sensory cue', 'Dim the room, change clothes, lower sound, or choose a familiar texture.'],
      ['3', 'Offer something steady', 'If it has been a while since eating or drinking, consider something familiar and manageable.'],
      ['4', 'Choose familiar over novel', 'A known show, audio, book or quiet activity may ask less of your attention.'],
    ],
    cta: { label: 'Begin a five-minute wind-down', action: 'wind-timer' },
  },
  research: {
    eyebrow: 'Evidence, without the hype',
    title: 'Nutrition can matter without becoming an ADHD cure claim.',
    intro: 'Dr Rachel Gow and colleagues have published preliminary clinic-sample research on nutrient status in neurodivergent people. It is valuable hypothesis-building work, but it does not establish that a particular meal, test or supplement treats ADHD.',
    steps: [
      ['Context', 'Preliminary means preliminary', 'The 2025 Gow co-authored study involved 57 people, only 10 adults, no matched control group and a private-clinic sample. Correlation cannot show that a nutrient level caused symptoms.'],
      ['Guideline', 'Australian guidance stays broader', 'The Australian ADHD guideline supports asking about diet, sleep and activity. It did not find enough high-quality evidence to recommend a specific dietary treatment.'],
      ['Practical', 'Adequacy and access still matter', 'Irregular eating, low intake, sensory barriers and medication-related appetite changes can add difficulty to a day, whatever their relationship to core ADHD symptoms.'],
      ['Scope', 'Who does what', 'Personal nutrition assessment sits with an APD. Medication and pathology sit with a GP or prescriber. Anchor offers general education and practical scaffolds.'],
    ],
    cta: { label: 'View Anchor’s evidence register', action: 'evidence' },
  },
}

export const fuelIdeas = [
  { id: 'toast', title: 'Toast + something alongside', description: 'Start with familiar toast. Add a topping or something on the side only if that feels workable.', effort: 'assemble', time: '5', texture: ['crunchy', 'soft'], temperature: ['warm'], equipment: ['toaster'], tags: ['familiar', 'flexible'] },
  { id: 'cereal', title: 'Cereal or muesli your way', description: 'Any cereal you reliably eat, with milk or an alternative—or dry if that is what works.', effort: 'none', time: '2', texture: ['crunchy', 'soft'], temperature: ['cold'], equipment: ['none'], tags: ['predictable', 'quick'] },
  { id: 'yoghurt', title: 'Yoghurt + an easy extra', description: 'Yoghurt on its own counts. Add fruit, cereal or nuts only if you want more staying power.', effort: 'none', time: '2', texture: ['smooth'], temperature: ['cold'], equipment: ['none'], tags: ['low appetite', 'quick'] },
  { id: 'smoothie', title: 'A drinkable option', description: 'A familiar smoothie, flavoured milk or nutrition drink can lower chewing and preparation demands.', effort: 'none', time: '2', texture: ['sippable', 'smooth'], temperature: ['cold', 'room'], equipment: ['none'], tags: ['low appetite', 'portable'] },
  { id: 'snack-plate', title: 'A no-cook snack plate', description: 'Choose two or three familiar things. Crackers, cheese, fruit, dips and packaged snacks can all belong.', effort: 'assemble', time: '5', texture: ['mixed', 'crunchy', 'soft'], temperature: ['cold', 'room'], equipment: ['none'], tags: ['choice', 'no cooking'] },
  { id: 'frozen', title: 'A reliable freezer option', description: 'Heat a familiar frozen meal or snack. Convenience is an access support, not a shortcut to apologise for.', effort: 'microwave', time: '10', texture: ['mixed', 'soft'], temperature: ['warm'], equipment: ['microwave'], tags: ['predictable', 'one step'] },
  { id: 'sandwich', title: 'A simple sandwich or wrap', description: 'Use one filling or several. Pre-sliced and packaged ingredients reduce steps.', effort: 'assemble', time: '5', texture: ['soft', 'mixed'], temperature: ['cold', 'room'], equipment: ['none'], tags: ['portable', 'flexible'] },
  { id: 'soup', title: 'Soup + something easy', description: 'Tinned, chilled or frozen soup is enough. Bread, crackers or cheese can sit alongside if available.', effort: 'microwave', time: '8', texture: ['smooth', 'soft'], temperature: ['warm'], equipment: ['microwave'], tags: ['low chewing', 'warm'] },
  { id: 'eggs', title: 'Eggs in the easiest form', description: 'Boiled, scrambled, pre-cooked or on toast—choose the version with the lowest barrier today.', effort: 'cook', time: '10', texture: ['soft'], temperature: ['warm', 'cold'], equipment: ['stove', 'microwave'], tags: ['flexible', 'familiar'] },
  { id: 'leftovers', title: 'Yesterday’s meal, today', description: 'A small portion of leftovers can be a useful bridge. Add something familiar if the full meal feels too much.', effort: 'microwave', time: '5', texture: ['mixed'], temperature: ['warm', 'cold'], equipment: ['microwave'], tags: ['less deciding', 'available'] },
  { id: 'delivery', title: 'Order the reliable thing', description: 'Delivered meals still count. Save a dependable order for the days choosing is hard.', effort: 'none', time: '20+', texture: ['mixed'], temperature: ['warm', 'cold'], equipment: ['none'], tags: ['no preparation', 'reliable'] },
  { id: 'emergency', title: 'The bag-or-drawer option', description: 'Keep a shelf-stable thing where you get stuck: bag, desk, car or bedside. Any reliable option can be an anchor.', effort: 'none', time: '1', texture: ['crunchy', 'soft', 'sippable'], temperature: ['room'], equipment: ['none'], tags: ['portable', 'visible'] },
]

export const nutritionCampaigns = [
  {
    id: 'nothing-sounds-manageable',
    label: 'Nothing sounds manageable',
    headline: 'Start with the texture—not the recipe.',
    body: 'A situation-first route into cold, warm, smooth, crunchy and no-preparation options.',
    action: 'nothing-manageable',
    cta: 'Find the least-demanding option',
    tone: 'rose',
  },
  {
    id: 'forgot-lunch-again',
    label: 'I forgot lunch again',
    headline: 'No making up for it. Just a next eating moment.',
    body: 'A shame-free restart built for the day that moved faster than body cues.',
    action: 'forgot-eat',
    cta: 'Take the two-minute restart',
    tone: 'clay',
  },
  {
    id: 'four-pm-return',
    label: 'The 4 pm appetite return',
    headline: 'Make the landing easier before the day gets louder.',
    body: 'General eating-access support for medication-affected appetite, with clear clinical boundaries.',
    action: 'med-appetite',
    cta: 'Open gentle support',
    tone: 'gold',
  },
  {
    id: 'same-meal-three-efforts',
    label: 'Same meal. Three effort levels.',
    headline: 'Cook it, assemble it, or use the packet.',
    body: 'The ingredients do not have to change for the number of steps to change.',
    action: 'meal:lentil-tomato-pasta',
    cta: 'See the fewest-step version',
    tone: 'olive',
  },
]

export const mealCards = [
  {
    id: 'salmon-sweet-potato',
    title: 'Salmon, egg + avocado plate',
    image: '/meals/real-salmon-egg-avocado.jpg',
    alt: 'Real photograph of a breakfast plate with smoked salmon, scrambled egg, avocado, greens and toast',
    photo: { photographer: 'Vitalii Kyktov', source: 'Unsplash', url: 'https://unsplash.com/photos/a-delicious-breakfast-plate-with-salmon-avocado-and-eggs-8arNIVWfn7M' },
    campaignHook: 'The component plate for when mixed food feels like too much information.',
    time: '25 min', effort: 'cook', appetite: 'steady', texture: ['mixed'],
    description: 'A component-style plate for days when separate, recognisable parts feel easier than a mixed dish.',
    ingredients: ['salmon—smoked, cooked or tinned', 'eggs in a preferred form', 'avocado or another spread', 'bread or another preferred carbohydrate', 'greens only if accessible', 'a familiar sauce or seasoning'],
    simplest: 'Use tinned salmon, a pre-boiled egg, bread and a familiar spread. Put each part down separately and leave out anything that adds friction.',
    why: [
      ['A steadier combination', 'Carbohydrate, protein and fat together can make this more sustaining than chasing a single “brain nutrient”.'],
      ['Omega-3 is present—not promised', 'Salmon provides long-chain omega-3 fats. That does not mean this plate treats ADHD, and supplement findings should not be transferred to a meal claim.'],
      ['Component meals can be accessible', 'Keeping textures separate may help when mixed textures or uncertainty are barriers.'],
    ],
    note: 'Choose alternatives for allergies, pregnancy guidance, cultural needs, sensory preferences and cost. Individual nutrition advice belongs with an APD.',
  },
  {
    id: 'eggs-avocado-toast',
    title: 'Eggs, avocado + tomato toast',
    image: '/meals/real-eggs-avocado-toast.jpg',
    alt: 'Real overhead photograph of egg and avocado on toast on a wooden board',
    photo: { photographer: 'Christina Branco', source: 'Unsplash', url: 'https://unsplash.com/photos/egg-on-top-of-avocado-and-bread-on-chopping-board-NY1iFRIERHA' },
    campaignHook: 'Breakfast whenever breakfast happens.',
    time: '10 min', effort: 'cook', appetite: 'steady', texture: ['soft', 'mixed'],
    description: 'Warm, familiar and flexible: keep one topping, use all three, or put each part alongside.',
    ingredients: ['bread you reliably eat', 'eggs in a preferred form', 'avocado or another spread', 'tomato if wanted', 'seasoning or sauce'],
    simplest: 'Use pre-boiled eggs or microwave scrambled eggs. Toast is optional; the parts can sit separately.',
    why: [
      ['Carbohydrate plus protein', 'The combination can offer a more sustaining eating opportunity than relying on coffee or waiting for strong hunger.'],
      ['Eggs contain choline', 'Choline has normal roles in the body and brain. Mentioning that role is not evidence that extra choline treats ADHD.'],
      ['Familiarity lowers decisions', 'A repeatable base can reduce planning, shopping and preparation steps.'],
    ],
    note: 'Eggs should be cooked and stored safely. Use alternatives that fit allergies, pregnancy guidance, culture, access and preference.',
  },
  {
    id: 'yoghurt-oats-berries',
    title: 'Yoghurt, oats + berries with toast',
    image: '/meals/real-oats-yoghurt.jpg',
    alt: 'Real photograph of a bowl of yoghurt and oats topped with strawberries',
    photo: { photographer: 'Joanna Stołowicz', source: 'Unsplash', url: 'https://unsplash.com/photos/a-bowl-of-yogurt-with-strawberries-on-top-Qze7zeiMz0A' },
    campaignHook: 'When chewing feels like work.',
    time: '5 min', effort: 'assemble', appetite: 'low', texture: ['smooth', 'soft', 'mixed'],
    description: 'An assemble-only option where every extra is optional and the base still counts.',
    ingredients: ['yoghurt or a preferred alternative', 'oats or familiar cereal', 'fresh or frozen fruit', 'nuts, seeds or another energy-dense extra if suitable', 'toast or another easy side'],
    simplest: 'Start with yoghurt alone. Add one extra only if it makes eating easier or more sustaining.',
    why: [
      ['Useful when appetite is quiet', 'Cool, soft or spoonable options may be easier for some people when chewing or strong smells feel demanding.'],
      ['Flexible staying power', 'A base plus carbohydrate and an optional energy-dense extra can be adapted to what is available.'],
      ['No ingredient has to earn its place', 'Fruit, toast, cereal and convenience products do not need an ADHD-specific benefit to belong.'],
    ],
    note: 'Whole nuts can be a choking risk for young children. Choose alternatives for allergies, swallowing safety and individual needs.',
  },
  {
    id: 'tofu-egg-fried-rice',
    title: 'Freezer-veg fried rice + an easy protein',
    image: '/meals/real-fried-rice.jpg',
    alt: 'Real photograph of a bowl of fried rice and vegetables on a domestic table',
    photo: { photographer: 'Kabita Darlami', source: 'Unsplash', url: 'https://unsplash.com/photos/a-bowl-filled-with-rice-and-vegetables-on-top-of-a-table-ZNSdgPrFGlY' },
    campaignHook: 'One pan. One decision. Enough for tomorrow.',
    time: '15 min', effort: 'cook', appetite: 'steady', texture: ['mixed'],
    description: 'A leftovers-friendly bowl that turns freezer and fridge basics into one warm meal.',
    ingredients: ['cooked rice—fresh or leftover', 'firm tofu', 'eggs', 'frozen mixed vegetables', 'spring onion if wanted', 'soy sauce and sesame oil'],
    components: [
      ['Rice', 'An accessible carbohydrate source that supplies energy. Using microwave rice or leftovers removes steps.'],
      ['Tofu + eggs', 'Provide protein; eggs also contain choline, which has normal roles in cell membranes and neurotransmission. This is nutrient function—not an ADHD treatment claim.'],
      ['Frozen vegetables', 'Add a range of nutrients and remove washing and chopping. Frozen vegetables are not a lesser choice.'],
      ['Soy sauce + sesame oil', 'Bring familiarity and flavour. Taste can be part of access, not an optional reward.'],
    ],
    simplest: 'Microwave a rice cup and frozen vegetables, add pre-marinated tofu, then stir through a cooked egg only if manageable.',
    why: [
      ['One pan, several components', 'Combining carbohydrate, protein and fat can create a more sustaining eating opportunity without tracking macros.'],
      ['Built for substitutions', 'Leave out a component, use a different protein or keep parts separate when mixed texture is not workable.'],
      ['No special ingredient required', 'Its value is being familiar, available and achievable—not being an ADHD cure.'],
    ],
    note: 'Cool rice promptly and refrigerate it; reheat until steaming. Choose gluten-free soy sauce or alternatives where needed.',
  },
  {
    id: 'banana-peanut-oats',
    title: 'Peanut butter, fruit + yoghurt oats',
    image: '/meals/real-peanut-fruit-oats.jpg',
    alt: 'Real photograph of a bowl of oats, fruit and peanut butter',
    photo: { photographer: 'Kate Mishchankova', source: 'Unsplash', url: 'https://unsplash.com/photos/a-bowl-filled-with-oats-kiwi-and-peanut-butter-Utas0Nj3XNs' },
    campaignHook: 'The five-minute option for a quiet appetite.',
    time: '5 min', effort: 'assemble', appetite: 'low', texture: ['smooth', 'soft'],
    description: 'A soft, low-chewing option that can be made ahead or assembled when appetite is quiet.',
    ingredients: ['rolled oats', 'yoghurt or preferred alternative', 'banana, kiwi or another familiar fruit', 'peanut butter or seed spread', 'milk or preferred alternative', 'cinnamon if liked'],
    components: [
      ['Oats + banana', 'Provide carbohydrate; oats also contribute fibre. The role here is nourishment and accessibility, not symptom control.'],
      ['Yoghurt + milk', 'Can contribute protein and calcium. Choose tolerated alternatives for allergy, culture, cost or preference.'],
      ['Peanut butter', 'Adds energy, fat and some protein in a small volume, which may be useful when appetite is quiet.'],
      ['Cinnamon', 'Adds a familiar flavour if wanted. It does not need a functional-health claim to belong.'],
    ],
    simplest: 'Use instant oats or a yoghurt cup, stir in peanut butter, and eat the banana separately—or skip any extra that becomes a barrier.',
    why: [
      ['Soft and predictable', 'Some people find cool, spoonable food easier when chewing, smell or decision load is high.'],
      ['Small-volume flexibility', 'The combination can be scaled down without turning a quiet appetite into a test.'],
      ['Prepare once, return later', 'A lidded container can reduce the number of decisions at the next eating opportunity.'],
    ],
    note: 'Peanuts are a common allergen. Use a tolerated alternative and follow individual swallowing and food-safety advice.',
  },
  {
    id: 'lentil-tomato-pasta',
    title: 'Lentil, tomato + spinach pasta',
    image: '/meals/real-lentil-pasta.jpg',
    alt: 'Real photograph of lentil pasta with tomato and summer vegetables in a white bowl',
    photo: { photographer: 'Bakd&Raw by Karolin Baitinger', source: 'Unsplash', url: 'https://unsplash.com/photos/white-ceramic-bowl-with-pasta-wotyhU6hWCc' },
    campaignHook: 'The meal that survives being forgotten.',
    time: '18 min', effort: 'cook', appetite: 'steady', texture: ['mixed', 'soft'],
    description: 'A familiar pasta base with pantry and freezer-friendly additions; every addition remains optional.',
    ingredients: ['pasta you reliably eat', 'tinned lentils', 'tomato pasta sauce', 'baby spinach—fresh or frozen', 'grated cheddar or alternative', 'olive oil'],
    components: [
      ['Pasta', 'Provides carbohydrate and a familiar base. Regular pasta, gluten-free pasta and other shapes can all work.'],
      ['Lentils', 'Contribute plant protein, fibre, iron and folate. Iron in food supports normal body functions; this meal does not diagnose or correct deficiency.'],
      ['Tomato + spinach', 'Add flavour and micronutrients. Jarred sauce and frozen spinach are legitimate access supports.'],
      ['Cheddar + olive oil', 'Add flavour and energy; cheddar also contributes protein and calcium.'],
    ],
    simplest: 'Heat a pouch of pasta or leftovers with jar sauce. Add tinned lentils only if opening and rinsing them is realistic today.',
    why: [
      ['A repeatable pantry meal', 'A short ingredient list can reduce shopping and planning demands.'],
      ['Fibre and protein are present', 'That describes the meal—not a guaranteed effect on attention, mood or medication.'],
      ['Texture can be adjusted', 'Blend the sauce, leave out spinach, choose a smaller pasta shape or serve components separately.'],
    ],
    note: 'Individual iron concerns need assessment by a GP and APD; food descriptions are not a recommendation for testing or supplements.',
  },
]

export const connectionCards = [
  { id: 'circling', theme: 'Say the thing', prompt: 'What have you been rehearsing so often that it feels as though you already said it?', bridge: 'Try: “This matters to me, and I have been overthinking how to begin.”' },
  { id: 'delay-meaning', theme: 'Say the thing', prompt: 'What meaning might the other person be making from your silence?', bridge: 'You can explain the delay without asking them to erase its impact.' },
  { id: 'channel', theme: 'Lower the pressure', prompt: 'Would this be easier to say, write, text or voice-note?', bridge: 'Choose the channel that helps contact happen—not the one that looks most impressive.' },
  { id: 'smallest-true', theme: 'Lower the pressure', prompt: 'What is the smallest true sentence that could open the conversation?', bridge: 'The opening sentence does not need to carry the entire history.' },
  { id: 'repair', theme: 'Repair', prompt: 'What part needs an apology, and what part only needs an honest explanation?', bridge: 'Repair can be proportionate. You do not need to disappear to show care.' },
  { id: 'reply', theme: 'Repair', prompt: 'If “sorry for the late reply” were enough, what would you answer next?', bridge: 'Respond to the actual question so the other person does not have to reassure you first.' },
  { id: 'invisible-load', theme: 'Be understood', prompt: 'What are you carrying in your head that nobody else can see?', bridge: 'Name one invisible task and one concrete kind of help.' },
  { id: 'sensory-need', theme: 'Be understood', prompt: 'What sensory need are you masking because you worry it will seem unreasonable?', bridge: 'A request can be specific: lower light, less background sound, more warning, or a pause.' },
  { id: 'capacity', theme: 'Capacity', prompt: 'What can you genuinely offer this week without borrowing from sleep, eating or recovery?', bridge: 'Capacity is information—not a moral grade.' },
  { id: 'pass', theme: 'Capacity', prompt: 'Which question do you want permission to pass on today?', bridge: 'Passing is an active boundary, not a failed conversation.' },
  { id: 'heard', theme: 'Connection', prompt: 'When do you feel most heard without having to perform clarity?', bridge: 'Notice the person, setting, pace and channel—not only the words.' },
  { id: 'return', theme: 'Connection', prompt: 'What helps you return after conflict without pretending nothing happened?', bridge: 'A small re-entry can be: “I am ready to come back to this when you are.”' },
]

export const programs = [
  { id: 'say-the-thing', pillar: 'connect', title: 'The say-it bridge', subtitle: 'Four minutes to move from rehearsal to contact.', minutes: 4, icon: 'MessageCircleMore', prompt: 'Write the smallest true sentence. The whole conversation does not need to fit inside it.' },
  { id: 'eat-with-me', pillar: 'nourish', title: 'Eat with me', subtitle: 'Ten quiet minutes of company while you begin.', minutes: 10, icon: 'Utensils', prompt: 'Bring the easiest available option close. There is nothing to perform here.' },
  { id: 'five-minute-start', pillar: 'begin', title: 'Borrow a beginning', subtitle: 'Five minutes of company with one visible action.', minutes: 5, icon: 'Play', prompt: 'Name only the first movement. Completion is not the price of starting.' },
  { id: 'tab-sort', pillar: 'regulate', title: 'Close the internal tabs', subtitle: 'Three minutes to park, mute and choose.', minutes: 3, icon: 'Layers3', prompt: 'Write the loops as fragments. You are making somewhere safe for them to wait.' },
  { id: 'hyperfocus-landing', pillar: 'begin', title: 'Land after hyperfocus', subtitle: 'Four minutes to return to time and body.', minutes: 4, icon: 'TimerReset', prompt: 'Look up. Name the time. Find the quiet body need before solving the lost hours.' },
  { id: 'repair-pause', pillar: 'connect', title: 'Pause before repair', subtitle: 'Four minutes between the feeling and the response.', minutes: 4, icon: 'HeartHandshake', prompt: 'The feeling can be intense without deciding what the moment means.' },
  { id: 'off-stage', pillar: 'regulate', title: 'Come off-stage', subtitle: 'Five minutes without performing capable.', minutes: 5, icon: 'BatteryLow', prompt: 'Nothing here needs to look productive, pleasant or impressive.' },
  { id: 'sensory-anchor', pillar: 'regulate', title: 'A quiet point of contact', subtitle: 'Three minutes with one tolerable sensation.', minutes: 3, icon: 'Hand', prompt: 'Notice texture, temperature and weight. Calm is not required.' },
  { id: 'four-minute-reset', pillar: 'move', title: 'Change the channel', subtitle: 'Four minutes of movement without measurement.', minutes: 4, icon: 'Footprints', prompt: 'Choose movement that feels available. Stillness is also allowed.' },
  { id: 'evening-soften', pillar: 'regulate', title: 'Soften the evening', subtitle: 'Five minutes to reduce input and close one loop.', minutes: 5, icon: 'Moon', prompt: 'The day can be unfinished and still be over.' },
]

export const evidenceNotes = [
  {
    id: 'lived-experience-review', label: 'Qualitative evidence', title: 'ADHD is lived as more than an attention problem',
    summary: 'A rapid review of 35 qualitative studies described interest-dependent attention, internal chaos, reduced structure, emotional dysregulation, relationship strain, irregular sleeping and eating, compensatory systems, low self-esteem and the value of ADHD-tailored support.',
    status: 'Lived experience', source: 'Frontiers in Psychiatry — rapid review', url: 'https://doi.org/10.3389/fpsyt.2022.949321', reviewed: '1 August 2026',
  },
  {
    id: 'gow-nutrition', label: 'Preliminary nutritional neuroscience', title: 'Interesting findings need their limitations beside them',
    summary: 'The 2025 Gow co-authored study reported nutrient insufficiencies and symptom correlations in a 57-person UK private-clinic sample. It included only 10 adults, had no matched control group and cannot show that the nutrient differences caused ADHD symptoms or that supplementation would improve them.',
    status: 'Preliminary', source: 'Frontiers in Nutrition — Hunter et al. (2025)', url: 'https://doi.org/10.3389/fnut.2025.1586925', reviewed: '1 August 2026',
  },
  {
    id: 'igg-testing', label: 'Clinical boundary', title: 'IgG food panels are not an Anchor pathway',
    summary: 'The Gow clinic paper reports IgG food testing, but ASCIA does not recommend IgG food testing for diagnosing food allergy or intolerance. Anchor will not translate those panels into elimination advice or a commercial testing pathway.',
    status: 'Do not use', source: 'ASCIA — Evidence-based allergy tests and treatments', url: 'https://www.allergy.org.au/patients/fast-facts/evidence-based-allergy-tests-and-treatments', reviewed: '2 August 2026',
  },
  {
    id: 'food-composition', label: 'Food composition', title: 'Ingredient explanations start with nutrient data',
    summary: 'Anchor uses the Australian Food Composition Database to describe what foods contain, then separates those nutrient facts from ADHD-specific claims.',
    status: 'Primary data', source: 'Food Standards Australia New Zealand — Australian Food Composition Database', url: 'https://www.foodstandards.gov.au/science-data/food-nutrient-databases/afcd', reviewed: '2 August 2026',
  },
  {
    id: 'aadpa-lifestyle', label: 'Established Australian guideline', title: 'Lifestyle questions belong in ADHD support',
    summary: 'The Australian ADHD guideline supports considering diet, sleep and physical activity and referring when challenges are identified. Its review did not support a single ADHD diet or universal nutrition protocol.',
    status: 'Guideline', source: 'Australian Evidence-Based Clinical Practice Guideline for ADHD', url: 'https://adhdguideline.aadpa.com.au/non-pharmacological/adhd-lifestyle-changes/', reviewed: '1 August 2026',
  },
  {
    id: 'rejection-sensitivity', label: 'Emerging lived-experience research', title: 'Rejection sensitivity is meaningful, but not settled science',
    summary: 'A small 2026 qualitative study of five university students described withdrawal, masking and bodily distress around perceived rejection. Anchor uses proportionate language because rejection sensitivity is not a formal ADHD diagnosis and the study is very small.',
    status: 'Emerging', source: 'PLOS ONE — qualitative exploration', url: 'https://doi.org/10.1371/journal.pone.0314669', reviewed: '1 August 2026',
  },
  {
    id: 'dietitian-scope', label: 'Professional scope', title: 'Personal nutrition support belongs with an APD',
    summary: 'Anchor offers general education only. Individual nutrition assessment, medical nutrition therapy and tailored dietary advice should sit with an appropriately qualified Accredited Practising Dietitian.',
    status: 'Scope', source: 'Dietitians Australia — Scope of Practice', url: 'https://dietitiansaustralia.org.au/working-dietetics/standards-and-scope/scope-practice-dietitians', reviewed: '1 August 2026',
  },
  {
    id: 'tga-purpose', label: 'Product governance', title: 'Intended purpose matters',
    summary: 'Anchor is designed as general wellbeing and education software. It does not diagnose ADHD, treat a disease, prescribe or monitor clinical care. New therapeutic features require regulatory review before release.',
    status: 'Governance', source: 'Therapeutic Goods Administration — Digital mental health software guidance', url: 'https://www.tga.gov.au/resources/guidance/understanding-digital-mental-health-tool-software-conditional-exclusion', reviewed: '1 August 2026',
  },
  {
    id: 'privacy', label: 'Privacy by design', title: 'Your entries stay in this browser',
    summary: 'This version does not create an account, transmit check-ins to the clinic or use them for advertising. Clearing browser data or changing devices can remove them.',
    status: 'Privacy', source: 'OAIC — Guide to health privacy', url: 'https://www.oaic.gov.au/privacy/privacy-guidance-for-organisations-and-government-agencies/health-service-providers/guide-to-health-privacy', reviewed: '1 August 2026',
  },
]

export const defaultRhythm = [
  { id: 'morning', label: 'Something in the morning', time: '08:00', enabled: true },
  { id: 'topup', label: 'A little top-up', time: '10:30', enabled: true },
  { id: 'midday', label: 'Midday nourishment', time: '13:00', enabled: true },
  { id: 'afternoon', label: 'Afternoon steady-up', time: '15:30', enabled: true },
  { id: 'evening', label: 'Evening meal', time: '18:30', enabled: true },
  { id: 'winddown', label: 'Gentle wind-down', time: '20:30', enabled: true },
]

export const supportLinks = [
  { label: 'Butterfly Foundation', detail: 'Eating disorders and body image · 8am–midnight AEST/AEDT, 7 days', phone: '1800 33 4673', href: 'tel:1800334673' },
  { label: 'Lifeline', detail: '24-hour crisis support', phone: '13 11 14', href: 'tel:131114' },
  { label: '13YARN', detail: '24/7 support for Aboriginal and Torres Strait Islander people', phone: '13 92 76', href: 'tel:139276' },
  { label: 'Emergency', detail: 'If you or someone else is in immediate danger', phone: '000', href: 'tel:000' },
]
