/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.smoke.jsonc --include-runtime=false smoke/worker-configuration.d.ts` (hash: 5cdeda63e66a7cd412ef010882648dc9)
interface __BaseEnv_Env {
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	ANCHOR_SMOKE_ACCEPTANCE_ENABLED: "true";
	SENTRY_DSN: string;
	ANCHOR_SMOKE_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ANCHOR_SMOKE_ACCEPTANCE_ENABLED" | "SENTRY_DSN" | "ANCHOR_SMOKE_TOKEN">> {}
}
