import type { Barrier, Moment, Support } from "./types.ts";

export const TAXONOMY_VERSION = "2026.08-v7.1";
export const CONSENT_VERSION = "2026.08-v7.1";

export const barrierLabels: Record<Barrier, { label: string; description: string }> = {
  "decision-load": { label: "Too many decisions", description: "Choosing is adding more work." },
  "sensory-load": { label: "Sensory load", description: "Texture, sound, light or smell is getting in the way." },
  activation: { label: "Starting feels blocked", description: "You know the step, but cannot make contact with it." },
  shame: { label: "Shame has grown", description: "The delay or mistake now feels bigger than the task." },
  "time-blindness": { label: "Time disappeared", description: "The moment moved past without your body or attention catching up." },
  words: { label: "The words will not settle", description: "You are rehearsing, editing or avoiding the message." },
};

export const moments: Moment[] = [
  {
    id: "forgot-eat",
    pillar: "nourish",
    title: "I forgot to eat",
    description: "The day moved and your body cues did not make it through.",
    defaultBarriers: ["time-blindness", "decision-load"],
    supportIds: ["reachable-next-bite", "temperature-texture-effort"],
    tags: ["appetite", "time", "nourishment"],
  },
  {
    id: "nothing-manageable",
    pillar: "nourish",
    title: "Nothing sounds manageable",
    description: "Food is available, but effort or sensory demand is too high.",
    defaultBarriers: ["sensory-load", "decision-load"],
    supportIds: ["temperature-texture-effort", "reachable-next-bite"],
    tags: ["sensory", "appetite", "effort"],
  },
  {
    id: "cant-start",
    pillar: "begin",
    title: "I know what to do. I still cannot begin.",
    description: "Knowing and starting are different jobs.",
    defaultBarriers: ["activation", "decision-load"],
    supportIds: ["visible-first-movement"],
    tags: ["task", "activation", "work"],
  },
  {
    id: "lost-day",
    pillar: "begin",
    title: "I started one thing and lost the day",
    description: "Deep focus needs a landing, not punishment.",
    defaultBarriers: ["time-blindness", "activation"],
    supportIds: ["hyperfocus-landing"],
    tags: ["hyperfocus", "transition", "body-cues"],
  },
  {
    id: "too-loud",
    pillar: "regulate",
    title: "Everything feels too loud",
    description: "The load needs to come down before another demand is added.",
    defaultBarriers: ["sensory-load", "decision-load"],
    supportIds: ["reduce-one-input"],
    tags: ["overload", "sensory", "pause"],
  },
  {
    id: "reply-late",
    pillar: "connect",
    title: "I left it too long to reply",
    description: "The shame grew while the message got no easier.",
    defaultBarriers: ["shame", "words"],
    supportIds: ["late-reply-bridge", "say-it-bridge"],
    tags: ["reply", "repair", "communication"],
  },
  {
    id: "rehearsing",
    pillar: "connect",
    title: "I keep rehearsing what I need to say",
    description: "Thinking about saying it has started to feel like saying it.",
    defaultBarriers: ["words", "shame"],
    supportIds: ["say-it-bridge", "late-reply-bridge"],
    tags: ["conversation", "communication", "repair"],
  },
  {
    id: "move-channel",
    pillar: "move",
    title: "I need to move or change the channel",
    description: "Movement can be a transition without becoming a target.",
    defaultBarriers: ["activation", "sensory-load"],
    supportIds: ["unmeasured-transition"],
    tags: ["movement", "transition", "no-measurement"],
  },
  {
    id: "research-hype",
    pillar: "understand",
    title: "I want the research without the wellness hype",
    description: "Clear evidence boundaries, without another promise to fix you.",
    defaultBarriers: ["decision-load", "shame"],
    supportIds: ["evidence-boundary"],
    tags: ["evidence", "education", "questions"],
  },
];

export const supports: Support[] = [
  {
    id: "reachable-next-bite",
    pillar: "nourish",
    title: "Make one option reachable",
    intro: "You do not need to repair the day. You only need a next eating moment that asks less of you.",
    steps: [
      "Bring one familiar option into sight. Packaged, frozen, delivered and assembled all count.",
      "Choose the option with the least preparation or clean-up.",
      "Add company—a familiar show, a quiet call or another person nearby—if beginning alone feels harder.",
    ],
    capacity: ["very-low", "some"],
    barriers: ["decision-load", "time-blindness", "activation"],
    modes: ["do", "connect"],
    boundary: "Ongoing appetite loss, dizziness, fainting, rapid weight change, vomiting or difficulty eating needs GP or prescriber support.",
    reviewStatus: "prototype",
  },
  {
    id: "temperature-texture-effort",
    pillar: "nourish",
    title: "Choose texture before recipe",
    intro: "Lower the sensory and decision load. Nourishment is the aim; impressive is not.",
    steps: [
      "Choose the least-demanding temperature: cold, room temperature or warm.",
      "Choose the most predictable texture: smooth, crunchy, soft, plain or sippable.",
      "Set the effort ceiling: open, assemble, microwave or cook a little.",
    ],
    capacity: ["very-low", "some", "steady"],
    barriers: ["sensory-load", "decision-load"],
    modes: ["do", "read"],
    boundary: "This is a food-access tool, not a dietary treatment for ADHD or an eating-disorder treatment plan.",
    reviewStatus: "prototype",
  },
  {
    id: "visible-first-movement",
    pillar: "begin",
    title: "Make contact the whole goal",
    intro: "This is not a motivation test. The first movement can be almost too small.",
    steps: [
      "Name a movement a camera could see: open the document, place the plate on the bench, find the email.",
      "Give it five minutes. Continuing is an option, not the price of starting.",
      "Leave one visible re-entry clue before you stop.",
    ],
    capacity: ["very-low", "some", "steady"],
    barriers: ["activation", "decision-load"],
    modes: ["do", "connect"],
    boundary: "Anchor does not monitor task completion or judge productivity.",
    reviewStatus: "prototype",
  },
  {
    id: "hyperfocus-landing",
    pillar: "begin",
    title: "Take a landing, not a lecture",
    intro: "Coming out of deep focus can feel like waking in the wrong room. Orient before you organise.",
    steps: [
      "Say the current time, day and place.",
      "Check bathroom, drink, something to eat, medication routine, pain and temperature.",
      "Contact one consequence, then save one line showing where to restart.",
    ],
    capacity: ["very-low", "some", "steady"],
    barriers: ["time-blindness", "activation"],
    modes: ["do", "read"],
    boundary: "Anchor does not change medication timing or provide clinical monitoring.",
    reviewStatus: "prototype",
  },
  {
    id: "reduce-one-input",
    pillar: "regulate",
    title: "Reduce one source of input",
    intro: "You do not have to organise the whole storm. Find one point of contact first.",
    steps: [
      "Let your eyes land on one still object.",
      "Lower one light, silence one notification or move somewhere quieter if you can.",
      "Notice the chair, floor or wall holding some of your weight. No special breathing required.",
    ],
    capacity: ["very-low", "some", "steady"],
    barriers: ["sensory-load", "decision-load"],
    modes: ["do", "read"],
    boundary: "This preference-based grounding option does not diagnose a nervous-system state or guarantee calm.",
    reviewStatus: "prototype",
  },
  {
    id: "late-reply-bridge",
    pillar: "connect",
    title: "Late is still allowed to become now",
    intro: "You do not need an elaborate explanation to re-enter contact.",
    steps: [
      "Read only the last message.",
      "Try: ‘I saw this, kept meaning to reply, and then felt awkward that it had been so long.’",
      "Answer the actual question without asking the other person to remove your discomfort.",
    ],
    capacity: ["very-low", "some", "steady"],
    barriers: ["shame", "words"],
    modes: ["do", "connect"],
    boundary: "Do not use direct-contact tools where coercion, abuse or family violence may make contact unsafe.",
    reviewStatus: "prototype",
  },
  {
    id: "say-it-bridge",
    pillar: "connect",
    title: "Make a bridge to the real conversation",
    intro: "We are not finding perfect words. We are making contact.",
    steps: [
      "Name the smallest true thing: ‘There is something I have been trying to find the words for.’",
      "Choose a lower-pressure channel and ask for a time to talk.",
      "Say what the delay means, then invite the other person’s preferred way to continue.",
    ],
    capacity: ["some", "steady"],
    barriers: ["words", "shame"],
    modes: ["do", "connect", "read"],
    boundary: "This is not for unsafe relationships or situations where direct contact could increase risk.",
    reviewStatus: "prototype",
  },
  {
    id: "unmeasured-transition",
    pillar: "move",
    title: "Move for the transition, not the score",
    intro: "Choose movement for sensation, alertness, release or a change of room—not to compensate for eating.",
    steps: [
      "Choose the need: release, grounding, alertness, play or a change of scene.",
      "Pick the smallest version: stand outside, stretch, walk to another room, shake out your hands.",
      "Stop when it has given enough. There is no ring to close.",
    ],
    capacity: ["very-low", "some", "steady"],
    barriers: ["activation", "sensory-load"],
    modes: ["do"],
    boundary: "Move only within your health, mobility and medical guidance. This is not exercise prescription.",
    reviewStatus: "prototype",
  },
  {
    id: "evidence-boundary",
    pillar: "understand",
    title: "Separate what is known from what is promised",
    intro: "Use a three-column check before a wellness claim becomes a plan.",
    steps: [
      "What is the source: guideline, systematic review, small study, expert opinion or marketing?",
      "What did it actually test—and in whom?",
      "What would you ask your GP, prescriber or Accredited Practising Dietitian before acting?",
    ],
    capacity: ["very-low", "some", "steady"],
    barriers: ["decision-load", "shame"],
    modes: ["read", "connect"],
    boundary: "Anchor provides general education only. It does not diagnose, prescribe supplements or replace individual clinical advice.",
    reviewStatus: "prototype",
  },
];
